Document: postgresql-musicbrainz-collate
Title: Debian postgresql-musicbrainz-collate Manual
Author: <insert document author here>
Abstract: This manual describes what postgresql-musicbrainz-collate is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/postgresql-musicbrainz-collate/postgresql-musicbrainz-collate.sgml.gz

Format: postscript
Files: /usr/share/doc/postgresql-musicbrainz-collate/postgresql-musicbrainz-collate.ps.gz

Format: text
Files: /usr/share/doc/postgresql-musicbrainz-collate/postgresql-musicbrainz-collate.text.gz

Format: HTML
Index: /usr/share/doc/postgresql-musicbrainz-collate/html/index.html
Files: /usr/share/doc/postgresql-musicbrainz-collate/html/*.html
